# Generated by Django 5.0.2 on 2024-02-27 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.TextField()),
                ('ping', models.IntegerField()),
                ('response_time', models.IntegerField()),
                ('cert', models.TextField()),
                ('status_code', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('cert_from', models.DateTimeField()),
                ('cert_to', models.DateTimeField()),
                ('domain_exp', models.DateTimeField()),
                ('days_to_domain_exp', models.IntegerField()),
            ],
        ),
    ]
