# Generated by Django 4.2.10 on 2024-02-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_alter_log_cert_from_alter_log_cert_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                (
                    "monitor_type",
                    models.CharField(
                        choices=[
                            ("http request", "Zapytanie HTTP"),
                            ("ping", "Ping"),
                            ("cron job", "Crone Job"),
                        ],
                        default="http request",
                        max_length=15,
                        verbose_name="Typ monitorowania",
                    ),
                ),
                ("request_timeout", models.FloatField(verbose_name="Czas odpowiedzi")),
                ("interval", models.FloatField(verbose_name="Interwał")),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data dodania"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="online",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("is_active", models.IntegerField(verbose_name="Czy aktywny?")),
            ],
            options={
                "verbose_name": "Monitor",
                "ordering": ["add_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="log",
            options={"ordering": ["request_date"], "verbose_name": "Log"},
        ),
        migrations.AlterField(
            model_name="log",
            name="cert",
            field=models.TextField(verbose_name="Certyfikat"),
        ),
        migrations.AlterField(
            model_name="log",
            name="cert_from",
            field=models.DateTimeField(null=True, verbose_name="Certyfikat ważny od"),
        ),
        migrations.AlterField(
            model_name="log",
            name="cert_to",
            field=models.DateTimeField(null=True, verbose_name="Certyfikat ważny do"),
        ),
        migrations.AlterField(
            model_name="log",
            name="days_to_domain_exp",
            field=models.IntegerField(verbose_name="Dni do wygaśnięcia domeny"),
        ),
        migrations.AlterField(
            model_name="log",
            name="domain",
            field=models.TextField(verbose_name="Domena"),
        ),
        migrations.AlterField(
            model_name="log",
            name="domain_exp",
            field=models.DateTimeField(null=True, verbose_name="Domena wygasa"),
        ),
        migrations.AlterField(
            model_name="log",
            name="ping",
            field=models.IntegerField(verbose_name="Ping"),
        ),
        migrations.AlterField(
            model_name="log",
            name="request_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data zapytania"),
        ),
        migrations.AlterField(
            model_name="log",
            name="response_time",
            field=models.IntegerField(verbose_name="Czas odpowiedzi"),
        ),
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="log",
            name="status_code",
            field=models.IntegerField(verbose_name="Numer Statusu"),
        ),
        migrations.AlterField(
            model_name="statuspage",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nazwa"),
        ),
        migrations.AlterField(
            model_name="statuspage",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                (
                    "monitor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.monitor",
                        verbose_name="ID Monitora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "ordering": ["monitor_id"],
            },
        ),
    ]
