# Generated by Django 4.2.10 on 2024-02-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0008_alter_monitor_request_timeout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={"ordering": ["email"], "verbose_name": "Email"},
        ),
        migrations.RemoveField(
            model_name="email",
            name="monitor_id",
        ),
        migrations.AddField(
            model_name="monitor",
            name="domain_or_ip",
            field=models.CharField(max_length=100, null=True, verbose_name="Domena lub IP"),
        ),
        migrations.AddField(
            model_name="monitor",
            name="emails",
            field=models.ManyToManyField(to="monitor.email", verbose_name="Emaile"),
        ),
        migrations.AddField(
            model_name="monitor",
            name="url",
            field=models.CharField(max_length=100, null=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.CharField(max_length=100, verbose_name="Adres e-mail"),
        ),
        migrations.CreateModel(
            name="EmailValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="monitor.email"),
                ),
                (
                    "monitor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.monitor",
                        verbose_name="ID Monitora",
                    ),
                ),
            ],
        ),
    ]
