# Generated by Django 4.2.10 on 2024-02-29 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0011_remove_monitor_domain_or_ip_remove_monitor_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="value_to_check",
            field=models.CharField(max_length=100, null=True, verbose_name="URL lub IP"),
        ),
        migrations.AlterField(
            model_name="statuspage",
            name="slug",
            field=models.SlugField(max_length=20, unique=True, verbose_name="Slug"),
        ),
    ]
