# Generated by Django 4.2.10 on 2024-02-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_monitor_status_page_id_alter_monitor_value_to_check_and_more'),
    ]

    operations = [
    ]
