# Generated by Django 4.2.10 on 2024-02-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_alter_log_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='domain',
        ),
        migrations.AddField(
            model_name='log',
            name='monitor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor.monitor', verbose_name='ID Monitora'),
            preserve_default=False,
        ),
    ]
