# Generated by Django 4.2.10 on 2024-02-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0018_monitor_ssl_monitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="ssl_monitor",
            field=models.BooleanField(default=False, verbose_name="Monitorować SSL?"),
        ),
    ]
