# Generated by Django 5.0.2 on 2024-03-06 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_alter_email_options_remove_log_monitor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalues',
            name='monitor_id',
        ),
        migrations.AddField(
            model_name='emailvalues',
            name='monitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor.monitor', verbose_name='Monitor'),
            preserve_default=False,
        ),
    ]
