# Generated by Django 5.0.2 on 2024-03-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0026_alter_monitor_monitor_type_apirequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apirequest",
            options={
                "ordering": ["-request_date"],
                "verbose_name": "Odpowiedź API",
                "verbose_name_plural": "Odpowiedzi API",
            },
        ),
        migrations.AlterField(
            model_name="monitor",
            name="value_to_check",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="URL lub IP"
            ),
        ),
    ]
